# Site settings
title: The Moon is Implicit
email: andrewek@gmail.com
description: > # this means to ignore newlines until "url:"
  Wherein Andrew Ek writes about software development, teaching, learning, and a few other things too
url: "https://andrewek.github.io" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
twitter_username: ektastrophe
github_username:  andrewek

permalink: pretty
paginate: 10

# Build settings
markdown: kramdown
highlighter: rouge

gems:
  - jekyll-sitemap
  - jekyll-paginate
